apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  namespace: resize-pv
spec:
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: storage-pvc
  containers:
    - name: storage-user
      image: nginx:alpine
      volumeMounts:
        - name: my-storage
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80