apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: webshop-frontend
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      nodeSelector:
        environment: production-gpu
      containers:
      - name: web-app-container
        image: nginx:latest
        ports:
        - containerPort: 80