script:
- prompt: "Please fix the health check issue with the deployment named 'webapp' in namespace 'health-check'"
setup: "setup.sh"
verifier: "verify.sh"
cleanup: "cleanup.sh"
difficulty: "medium"
